import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ReduxProvider} from "@/store/reduxProvider";
// import {ReduxProvider}
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Navbar />
           {/* <div className="relative h-full w-full bg-gray-100">
          <div className="bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)] bg-[size:14px_24px] min-h-[87.5vh]"> */}
        {children}
        {/* </div>
        </div> */}
        <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
